### PR TITLE
Update mastermind.py

### PR DESCRIPTION
**Pull request by JDeepD**

### CODE REVIEW

**Comment by Mastermind-sap** [comment]
@Nova-Striker Your PR is not enhancing something. Even if you give an else clause in the choice input section the game will run again because its not breaking from the while loop. So, it will just print "Wrong input value" and nothing else. Moreover you changed the condition for the if and elif statement, but the conditions are very similar while my one will take a "ye" also as an yes input your will not. So, there is no valid contribution.

**Comment by JDeepD** [comment]
Okay 👍

**Comment by JDeepD** [comment]
FYI,  putting `list("yes")` would make it `["y","e","s"]` meaning , `a in list("yes")` will evaluate to `True` only if a is any one of `y` , `e` or `s`. (Will not work if `a = "ye"`) as you mentioned in your thread. (It will also not work if `a="yes"`) . So if you want to make the condition with only `y` or `n`, why not just put only those instead of `list("yes")` ?

**Comment by Mastermind-sap** [comment]
yeah you have got a point! Thanks! Please create a new PR as I cannot reopen this one due to some issue. I will accept your PR.

**Pull request closed without merging**
